"""
Django settings for inventory_system project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os
import sys

# =========================================================
# 1. PORTABLE EXE CONFIGURATION (CRITICAL FIX)
# =========================================================
# We must split paths into two types:
#   ASSETS_DIR: Read-only files extracted by PyInstaller (Templates, Static)
#   DATA_DIR:   Read-write files that must persist (Database)

if getattr(sys, 'frozen', False):
    # Running as compiled EXE
    ASSETS_DIR = Path(sys._MEIPASS)      # Temp folder where PyInstaller extracts files
    DATA_DIR = Path(sys.executable).parent # Folder where the EXE is located
else:
    # Running normally (python manage.py runserver)
    ASSETS_DIR = Path(__file__).resolve().parent.parent
    DATA_DIR = ASSETS_DIR

# Use ASSETS_DIR as the default base for internal Django things
BASE_DIR = ASSETS_DIR


# =========================================================
# 2. CORE SETTINGS
# =========================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nl%5a8l^e$pqfbe@os=(narxoo0oa(*ud*tnoxim90%b+_gs7&'

# SECURITY WARNING: DEBUG must be False for the EXE to serve static files correctly via Whitenoise
DEBUG = False 

ALLOWED_HOSTS = ['*']  # Allow running on any local IP

LOGIN_REDIRECT_URL = "/api/"
LOGOUT_REDIRECT_URL = "/api/auth/login/"


# =========================================================
# 3. APPLICATIONS & MIDDLEWARE
# =========================================================

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',  # Whitenoise must be high up
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your Apps
    "rest_framework",
    "core",
    "drf_spectacular",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS first
    "django.middleware.security.SecurityMiddleware",
    
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Whitenoise second (Serves React App)

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'inventory_system.urls'


# =========================================================
# 4. TEMPLATES (React Integration)
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ✅ FIX: Point to ASSETS_DIR (Temp folder) for templates
        'DIRS': [os.path.join(ASSETS_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_system.wsgi.application'


# =========================================================
# 5. DATABASE
# =========================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # ✅ FIX: Point to DATA_DIR (EXE folder) so data is saved next to the app
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}


# =========================================================
# 6. PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =========================================================
# 7. INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =========================================================
# 8. STATIC FILES (React Assets)
# =========================================================

STATIC_URL = '/static/'
# ✅ FIX: Use ASSETS_DIR for static files location
STATIC_ROOT = os.path.join(ASSETS_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(ASSETS_DIR, 'static'),  
]

# Compression and caching support
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# =========================================================
# 9. API & CORS SETTINGS
# =========================================================

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True 

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny"
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.CsrfExemptSessionAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Inventory Management API",
    "DESCRIPTION": "Offline-first Inventory & Billing System API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}