# Generated by Django 6.0.1 on 2026-03-09 13:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_billitem_purchase_price_product_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest_purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
